### PR TITLE
Add support for running as NBD server

### PR DESCRIPTION
**Pull request by Nikratio**
See new `README_nbd.txt`file for why this could be useful.

### CODE REVIEW

**Comment by archiecobbs** [comment]
Oops, sorry - I accidentally pushed my local changes to your repository somehow. I thought that would not be possible but I guess github allows it. Reverting now...

**Comment by archiecobbs** [comment]
OK now that's fixed, please checkout the `nbd` branch in my repo (commit 767dd1b3) and see if the updated build works for you.

**Comment by Nikratio** [comment]
Yes, your branch compiles fine with autotools.

Note that you can drop the versioned dependency on nbdkit to at least 1.24.1, probably lower (but I didn't test with anything older).

**Comment by Nikratio** [comment]
Follow-up: it compiles fine, but it does not run:

```
nikratio@vostro ~/i/s3backer (nbd)> nbdkit .libs/nbdkit-s3backer-plugin.so --help
nbdkit: error: cannot open plugin '.libs/nbdkit-s3backer-plugin.so': .libs/nbdkit-s3backer-plugin.so: undefined symbol: comp_algs
Use 'nbdkit --help' or read the nbdkit(1) manual page for documentation.
```

**Comment by archiecobbs** [comment]
That problem is fixed by 6e9f7cc, but there are some others. I'm still looking at it.

**Comment by archiecobbs** [comment]
Did some reformatting & other clean ups in 96f61b6. Now it at least runs and starts, but doesn't quite work or I don't know what I'm doing.

**Comment by Nikratio** [comment]
Can you clarify what you mean by "doesn't quite work"? Here's how I have been testing this:

```
nbdkit --unix nbd_socket_reg --foreground --threads 16 \
       --filter=exitlast \
       ./nbdkit-s3backer-plugin.so \
       statsfile=/dev/stdout \
       conffile=s3backer.conf region=eu-west-2 nikratio-test/zfs &

sleep 5

sudo nbd-client -unix nbd_socket_reg --threads 16 /dev/nbd0

echo 512 | sudo tee /sys/block/nbd0/queue/max_sectors_kb
sudo zpool import -d /dev/nbd0 -R /mnt/remote remote

# (do stuff)

sudo zpool export remote
sudo nbd-client -d /dev/nbd0

```

**Comment by archiecobbs** [comment]
Wow, with commit ce862fcc it works...

`demo.conf`:
```
# Runs the demo - NBDKit version

--listBlocks
--readOnly
--debug
s3backer-demo
```

Window 1:
```
$ ./autogen
...
$ ./configure && make -j
...
$ nbdkit --unix nbd_socket_reg --foreground --threads 16 --filter=exitlast .libs/nbdkit-s3backer-plugin.so configFile=demo.conf 
nbdkit: auto-detecting block size and total file size...
nbdkit: auto-detected block size=4k and total size=20m
```

Window 2 (root):
```
$ nbd-client -unix nbd_socket_reg /dev/nbd0 -block-size 4096 -nofork
Warning: the oldstyle protocol is no longer supported.
This method now uses the newstyle protocol with a default export
Negotiation: ..size = 20MB
bs=4096, sz=20971520 bytes
```

Window 3 (root):
```
$ mount -o ro /dev/nbd0 mnt2/
$ ls -l mnt2/
total 80
drwxr-xr-x 2 root root  4096 Jun 30  2008 devices/
drwxr-xr-x 2 root root  4096 Jun 30  2008 fifos/
drwxr-xr-x 2 root root 16384 Jun 30  2008 lost+found/
-rw-r--r-- 1 root root   369 Jun 30  2008 README
drwxr-xr-x 2 root root  4096 Jun 30  2008 symlinks/
-rw-r--r-- 1 root root 48688 Aug  4  2008 TellurideAirport.jpg
```

Nice work!

**Comment by Nikratio** [comment]
Ok, this is now rebased against `nbd`.

**Comment by archiecobbs** [comment]
Thanks.

**Comment by archiecobbs** [comment]
Now regarding this PR:
* `Merge "cleanup" and "unload" callbacks` - this is merged in
* `Add Meson build config file` - not needed for general users, correct?
* `Accept arbitrary s3backer parameters on the nbdkit command line` - I don't think this is the right approach; a single config file is cleaner: `nbdkit s3backer myconfig.conf`
* `Added example script to create NBD-based zpool` - this is fine

**Comment by Nikratio** [comment]
- Meson support is not required for NBD, no. I much prefer working with Meson over Autotools and I think others do too. So I was hoping this could be merged independently as an alternative build system for those who prefer it.
- If support for s3backer command line parameters is not merged, then the example script will need to be modified to write temporary config files - which I think will nicely illustrate the drawbacks of this approach. I'm also a bit surprised that you consider this the wrong approach for NBD, but the right approach for FUSE - wouldn't the same arguments apply to the `s3backer` command? Why is this accepting all the parameters instead of just one config file? But it's of course your call.
-

**Comment by archiecobbs** [comment]
Regarding parameters, what's the reason for the `s3b_` prefix?

**Comment by Nikratio** [comment]
To prevent accidental collisions with parameters used by nbdkit itself, or any nbdkit filters. Since s3backer accepts so many options, I thought this might be the safer choice.

**Comment by Nikratio** [comment]
I believe parameters that are accepted by filters are not passed to the plugin in the first place. For example, if you specified a `blocksize` parameter and used the `blocksize` filter and the s3backer plugin, s3backer would never see the `blocksize` parameter.

**Comment by archiecobbs** [comment]
> I believe parameters that are accepted by filters are not passed to the plugin in the first place. For example, if you specified a blocksize parameter and used the blocksize filter and the s3backer plugin, s3backer would never see the blocksize parameter.

OK, in that case we could make the `s3b_` prefix optional, right? (Currently it's required)

In other words, the s3backer plugin would simply strip it off - if present - and then proceed.

**Comment by archiecobbs** [comment]
Thinking more about it I agree now that we can support all of the normal `s3backer(1)` command line flags as `nbdkit(1)` parameters. It doesn't hurt anything to include this support. I'm working on that now (on my version) and included the `s3b_` prefix which will be optional.

I'm also going to add an `--nbd` flag to the standard `s3backer` executable which will enable execution via `nbdkit(1)` using a simple "trampoline" to `execve(2)` since this will be relatively easy:
```
SYNOPSIS
     s3backer [options] bucket[/subdir] /mount/point

     s3backer --nbd [options] bucket[/subdir] socket-file

     s3backer --nbd [options] bucket[/subdir] [ip-addr:]port

     s3backer --test [options] dir /mount/point

     s3backer --erase [options] bucket[/subdir]

     s3backer --reset-mounted-flag [options] bucket[/subdir]
```

**Comment by archiecobbs** [comment]
Just pushed some updates.

**Comment by Nikratio** [comment]
Yes - making the `s3b_` prefix optional sounds like a good idea, thanks!

The `--nbd` option to s3backer is also an interesting thought. Have you thought about having it run not just `nbdkit` but also `nbd-client` for convenience?

**Comment by archiecobbs** [comment]
> Have you thought about having it run not just nbdkit but also nbd-client for convenience?

Interesting idea... I will look into that.

**Comment by archiecobbs** [comment]
See 2e0b110.

**Comment by archiecobbs** [comment]
Merged `nbd` branch in to `master` branch in 24db94df.

**Pull request closed without merging**
